### ISSUE TITLE
Missing weather icon

### ISSUE THREAD

**Issue by SixBytesUnder** [SixBytesUnder/infoboard#21]
Missing weather icon causes console error and prevents 7-day weather forecast from showing.
Example of missing icon error:
```
Error: Cannot find module './images/breezy.svg'
    at c (2adb700.js:1)
    at o (2adb700.js:1)
    at f.loadImage (2adb700.js:1)
    at 2adb700.js:1
    at f.Ae [as _l] (5c016e5.js:2)
    at f.<anonymous> (2adb700.js:1)
    at f.t._render (5c016e5.js:2)
    at f.r (5c016e5.js:2)
    at _n.get (5c016e5.js:2)
    at _n.run (5c016e5.js:2)
```
Handle missing icons so they don't break the functionality.

**Comment by SixBytesUnder** [comment]
Issue no longer present after migrating climacell API to v4 in 28b44acca722b0162e656e918c195d6e3be4eb25
